name: X86_64_OpenWrt

on:
  workflow_dispatch:
    inputs:
      LAN_IP:
        description: 'Set LAN IP Address'
        required: true
        default: '192.168.1.1'
#  schedule:
#    - cron: 0 16 * * 5

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        git config --global user.name 'actions'
        git config --global user.email 'action@github.com'
        
    - name: Show system
      run: |
        echo -e "\n\e[1;32mCPU:\e[0m"
        echo "$(grep 'model name' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}') ($(grep 'cpu MHz' /proc/cpuinfo | head -1 | awk -F ': ' '{print $2}')MHz) x $(grep processor /proc/cpuinfo  | wc -l)"
        echo -e "\n\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\n\e[1;32mStorage:\e[0m"
        df -Th / /mnt
        echo -e "\n\e[1;32mSystem:\e[0m"
        lsb_release -a
        echo -e "\n\e[1;32mKernel:\e[0m"
        uname -a
        echo
        
    - name: Free disk space
      uses: oppen321/actions@free-disk

    - name: Checkout
      uses: actions/checkout@main

    - name: Build System Setup
      uses: oppen321/actions@openwrt-build-setup

    - name: Install LLVM
      uses: oppen321/actions@install-llvm
      
    - name: Prepare Mixedwrt
      run: |
        sudo chown -R runner:runner /home/runner/work/OpenWrt-Action
        cp -r ./SCRIPTS/X86/. ./SCRIPTS/
        cp -r ./SCRIPTS/. ./
        /bin/bash 01_get_ready.sh
        
    - name: Prepare Package
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        cp -r ../SCRIPTS/. ./
        /bin/bash 02_prepare_package.sh
        /bin/bash 03_custom_settings_x86.sh
#        /bin/bash 04_remove_upx.sh
        
    - name: QTMDFW4
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        cp -rf ../SCRIPTS/X86/config.seed .config
        
#    - name: Convert Translation
#      working-directory: ${{ github.workspace }}/openwrt
#      run: |
#        /bin/bash 05_convert_translation.sh
        
#    - name: Add ACL
#      working-directory: ${{ github.workspace }}/openwrt
#      run: |
#        /bin/bash 06_create_acl_for_luci.sh -a
        
#    - name: Fix Permissions
#      working-directory: ${{ github.workspace }}/openwrt
#      run: |
#        sudo -E chmod -R 755 ./07_fix_permissions.sh
#        /bin/bash 07_fix_permissions.sh
        
    - name: Make Config
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        make defconfig
        
    - name: Get Architecture
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        TARGET_DEVICE_ARCH="$(grep "^CONFIG_TARGET_.*_.*=y$" ".config" | head -n 1 | sed 's/^CONFIG_TARGET_//g' | awk -F '_' '{print $1}')"
        echo "TARGET_DEVICE_ARCH=${TARGET_DEVICE_ARCH}" >>$GITHUB_ENV
        latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+\-*r*c*[0-9]*.tar.gz" | sed -n '/[2-9][4-9]/p' | sed -n 1p | sed 's/.tar.gz//g' | sed 's/v//g')"
        echo "latest_release=${latest_release}" >>$GITHUB_ENV
        
    - name: Cache
      uses: HiGarfield/cachewrtbuild@main
      with:
        mixkey: ${{ env.TARGET_DEVICE_ARCH }}
        prefix: ${{ github.workspace }}/openwrt
        
    - name: Set Variables
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        cat vermagic
        COMMIT_AUTHOR=$(git show -s --date=short --format="ä½œè€…: %an")
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
        COMMIT_DATE=$(git show -s --date=short --format="æ—¶é—´: %ci")
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
        COMMIT_MESSAGE=$(git show -s --date=short --format="å†…å®¹: %s")
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        COMMIT_HASH=$(git show -s --date=short --format="hash: %H")
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        
    - name: Set default LAN IP
      run: |
        cd ${{ github.workspace }}/openwrt
        SET_IP=${{ github.event.inputs.LAN_IP }}
        if [[ $SET_IP =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; then
            #ä¿®æ”¹é»˜è®¤IPåœ°å€
            sed -i "s/192\.168\.[0-9]*\.[0-9]*/$SET_IP/g" package/base-files/files/bin/config_generate
            echo "Set LAN IP Address: $SET_IP"
        else
            echo "Invalid IP address, use default."
        fi
        
    - name: Make Download
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        make download -j50
        
    - name: Compile Openwrt
      working-directory: ${{ github.workspace }}/openwrt
      id: compileopenwrt
      continue-on-error: true
      run: |
        make -j$(nproc)
        sed -n 's/.*lan) ipad=${ipaddr:-"\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)"} ;;.*/\1/p' package/base-files/files/bin/config_generate | head -n 1 > IP_ADDR
        [ -s IP_ADDR ] && echo "IP_ADDR=$(cat IP_ADDR)" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
        echo "TAG_TIME=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
        
    - name: If Error
      working-directory: ${{ github.workspace }}/openwrt
      if: steps.compileopenwrt.outcome == 'failure'
      run: |
        cat ./.config
        echo '================================================================'
        make -j1 V=s
        
    - name: Organize Files
      id: Organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/*
        cat sha256sums
        mv -f openwrt/bin/packages/*/*/*.ipk packages
        tar -zcf Packages.tar.gz packages
        rm -rf packages
        echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
        
#    - name: Organize Files
#      id: Organize
#      run: |
#        cd openwrt/bin/targets/x86/64
#        rm -rf packages
#        echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
#        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
            
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.FILE_DATE }}-OpenWrt-${{ env.latest_release }}
        allowUpdates: true
        prerelease: false
        tag: ${{ env.TAG_TIME }}-${{ env.latest_release }}
        commit: "24.10"
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE_PATH }}/*
        body: |
          **This is OpenWrt Firmware for X86_64**
          ### ğŸ“’ å›ºä»¶ä¿¡æ¯
          - ğŸ’» å¹³å°æ¶æ„: X86_64
          - âš½ å›ºä»¶æºç : https://github.com/openwrt/openwrt
          - ğŸ’ æºç åˆ†æ”¯: ${{ env.latest_release }}
          - ğŸš€ å†…æ ¸ç‰ˆæœ¬: ${{ env.KERNEL }}
          - ğŸŒ é»˜è®¤åœ°å€: ${{ env.IP_ADDR }}
          - ğŸ”‘ é»˜è®¤å¯†ç : password
          ### ğŸ§Š å›ºä»¶ç‰ˆæœ¬
          - å›ºä»¶ç¼–è¯‘å‰æœ€åä¸€æ¬¡â¦[ä¸»æºç ](https://github.com/openwrt/openwrt)æ›´æ–°è®°å½•
          - ${{ env.COMMIT_AUTHOR }}
          - ${{ env.COMMIT_DATE }}
          - ${{ env.COMMIT_MESSAGE }}
          - ${{ env.COMMIT_HASH }}
          
    - name: Print Disk Space After
      run: df -h

